name = "Try With Finally";
description = "Indicates if a try use a finally statement.

<?php

try {
    $a = doSomething();
} catch (Throwable $e) {
    // Fix the problem
} finally {
    // remove $a anyway
    unset($a);
}

?>

See also `Exceptions <https://www.php.net/manual/en/language.exceptions.php>`_, to learn about catching an exception.
";
clearphp = "";
phpversion = "5.5+";
severity = "";
timetofix = "";
exakatSince = "0.8.4";

precision = "P_VERY_HIGH"